project:
  type: website

website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    logo: /img/digi-epi transparent.png
    left: 
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: Syllabus.qmd
        text: Resource Speakers
      - href: bioinformatics.qmd
        text: Bioinformatics and Digital Epidemiology
      - text: Workshop Materials
        menu:
          - module1/module1.qmd
          - module2/module2.qmd
          - module3/module3.qmd
          - module4/module4.qmd
          - module5/module5.qmd
          - module6/module6.qmd
          - Pre-Test/Post-Test.qmd
          - Workshop Evaluation.qmd
      - href: Syllabus.qmd 
        text: Got a question?


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: twitter 
        href: https://twitter.com/TheCGPS


format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
